name: Page Deployment

on:
  page_build:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
    
